/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    veiculos: Veiculo;
    marcas: Marca;
    modelos: Modelo;
    servicos: Servico;
    avaliacoes: Avaliacoe;
    eventos: Evento;
    midia: Midia;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    veiculos: VeiculosSelect<false> | VeiculosSelect<true>;
    marcas: MarcasSelect<false> | MarcasSelect<true>;
    modelos: ModelosSelect<false> | ModelosSelect<true>;
    servicos: ServicosSelect<false> | ServicosSelect<true>;
    avaliacoes: AvaliacoesSelect<false> | AvaliacoesSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    midia: MidiaSelect<false> | MidiaSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'pagina-inicial': PaginaInicial;
    'textos-remap': TextosRemap;
    empresa: Empresa;
    seo: Seo;
  };
  globalsSelect: {
    'pagina-inicial': PaginaInicialSelect<false> | PaginaInicialSelect<true>;
    'textos-remap': TextosRemapSelect<false> | TextosRemapSelect<true>;
    empresa: EmpresaSelect<false> | EmpresaSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cada linha é uma versão de carro com os números de original, Stage 1, Stage 2 e Stage 3. Desmarque "Aparece no site" para esconder sem apagar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "veiculos".
 */
export interface Veiculo {
  id: number;
  published?: boolean | null;
  /**
   * Fica em /remap/<endereço>. Preenchido sozinho a partir da marca e da versão.
   */
  slug?: string | null;
  origin?: ('kaiju' | 'armada') | null;
  title?: string | null;
  /**
   * Escolha na lista. Marca nova? Clique no + ao lado.
   */
  brand: number | Marca;
  /**
   * Escolha a marca primeiro. Modelo novo? Clique no + ao lado.
   */
  family: number | Modelo;
  /**
   * Ex.: Golf GTI 2.0 TSI
   */
  version: string;
  /**
   * Opcional. Ex.: 2015 a 2020
   */
  years?: string | null;
  category: 'turbo-gasolina' | 'diesel' | 'aspirado';
  /**
   * Comece sempre pelo Original. Os ganhos em % são calculados sozinhos.
   */
  stages?:
    | {
        name: 'Original' | 'Stage 1' | 'Stage 2' | 'Stage 3';
        cv: number;
        kgfm: number;
        /**
         * Opcional. Só quando não é um número simples: 300+, 380/440
         */
        cvText?: string | null;
        /**
         * Opcional. Ex.: 56,1
         */
        kgfmText?: string | null;
        /**
         * Uma peça por linha. Ex.: Downpipe (Enter) Intercooler
         */
        upgrades?: string | null;
        id?: string | null;
      }[]
    | null;
  engine?: string | null;
  /**
   * Uma linha por item. Ex.: Câmbio → DSG; Tração → Dianteira.
   */
  specs?:
    | {
        /**
         * Ex.: Câmbio
         */
        label: string;
        /**
         * Ex.: DSG
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  notes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. A arte do Instagram com os números desta versão.
   */
  poster?: (number | null) | Midia;
  /**
   * Opcional. Link do post de onde saíram os números.
   */
  instagram?: string | null;
  instagramDate?: string | null;
  /**
   * Opcional. Aparece como destaque na página da versão.
   */
  publishedResult?: {
    title?: string | null;
    text?: string | null;
    instagram?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * As marcas do catálogo. Mudar o nome aqui muda em todas as versões da marca.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas".
 */
export interface Marca {
  id: number;
  /**
   * Como aparece no site. Ex.: Volkswagen, Mercedes-Benz
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Os modelos agrupam as versões na página de cada marca. Ex.: Golf, Série 3, Hilux.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos".
 */
export interface Modelo {
  id: number;
  /**
   * Não achou a marca? Clique no + para criar.
   */
  brand: number | Marca;
  /**
   * Sem a marca. Ex.: Golf, Série 3, A3 / S3 / RS3
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Todas as fotos e vídeos do site. Troque uma foto aqui e ela muda em todo lugar onde aparece.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia".
 */
export interface Midia {
  id: number;
  /**
   * O que aparece na foto. Ajuda o Google e quem usa leitor de tela. Ex.: "Golf GTI branco no elevador".
   */
  alt: string;
  /**
   * Opcional. Perfil de quem fotografou, quando a foto não é da Kaiju. Ex.: @fotografo
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * A lista de serviços da página inicial. Arraste para mudar a ordem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicos".
 */
export interface Servico {
  id: number;
  _order?: string | null;
  name: string;
  lead: string;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  photo: number | Midia;
  /**
   * Completa a mensagem "Olá, Kaiju! Quero um orçamento de ___". Deixe vazio para esconder o botão Orçamento.
   */
  cta?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Copie o texto da avaliação como o cliente escreveu no Google. Arraste para mudar a ordem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avaliacoes".
 */
export interface Avaliacoe {
  id: number;
  _order?: string | null;
  author: string;
  rating: '5' | '4' | '3' | '2' | '1';
  text: string;
  photos?: (number | Midia)[] | null;
  /**
   * No Google Maps, abra a avaliação, toque em Compartilhar e cole o link aqui.
   */
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eventos da seção "Na rua". O site mostra as 5 primeiras fotos de cada um.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Como deve aparecer. Ex.: 11 e 12 de abril de 2026
   */
  date: string;
  place: string;
  text: string;
  photos: (number | Midia)[];
  /**
   * Opcional. Ex.: https://www.instagram.com/p/DX-A6ZjDym-/
   */
  instagram?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem pode entrar no painel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'veiculos';
        value: number | Veiculo;
      } | null)
    | ({
        relationTo: 'marcas';
        value: number | Marca;
      } | null)
    | ({
        relationTo: 'modelos';
        value: number | Modelo;
      } | null)
    | ({
        relationTo: 'servicos';
        value: number | Servico;
      } | null)
    | ({
        relationTo: 'avaliacoes';
        value: number | Avaliacoe;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null)
    | ({
        relationTo: 'midia';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "veiculos_select".
 */
export interface VeiculosSelect<T extends boolean = true> {
  published?: T;
  slug?: T;
  origin?: T;
  title?: T;
  brand?: T;
  family?: T;
  version?: T;
  years?: T;
  category?: T;
  stages?:
    | T
    | {
        name?: T;
        cv?: T;
        kgfm?: T;
        cvText?: T;
        kgfmText?: T;
        upgrades?: T;
        id?: T;
      };
  engine?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  notes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  poster?: T;
  instagram?: T;
  instagramDate?: T;
  publishedResult?:
    | T
    | {
        title?: T;
        text?: T;
        instagram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas_select".
 */
export interface MarcasSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos_select".
 */
export interface ModelosSelect<T extends boolean = true> {
  brand?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicos_select".
 */
export interface ServicosSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  lead?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  photo?: T;
  cta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avaliacoes_select".
 */
export interface AvaliacoesSelect<T extends boolean = true> {
  _order?: T;
  author?: T;
  rating?: T;
  text?: T;
  photos?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  date?: T;
  place?: T;
  text?: T;
  photos?: T;
  instagram?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia_select".
 */
export interface MidiaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Textos e fotos de cada parte da página inicial, na ordem em que aparecem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicial".
 */
export interface PaginaInicial {
  id: number;
  hero: {
    line1: string;
    line2: string;
    /**
     * Vem no fim da 2ª linha, com o contorno vermelho.
     */
    highlight: string;
    lead: string;
    primaryButton: string;
    secondaryButton: string;
    /**
     * MP4 curto, sem som, até ~5 MB. Toca em loop.
     */
    videoWide?: (number | null) | Midia;
    /**
     * Mesmo enquadramento do vídeo, aparece enquanto ele carrega.
     */
    posterWide?: (number | null) | Midia;
    /**
     * MP4 vertical, sem som.
     */
    videoTall?: (number | null) | Midia;
    posterTall?: (number | null) | Midia;
  };
  about: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    motto?: string | null;
    signatureName?: string | null;
    signatureTagline?: string | null;
    signatureLine?: string | null;
    facts?:
      | {
          term: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    mainPhoto: number | Midia;
    secondPhoto?: (number | null) | Midia;
    mainCaption?: string | null;
  };
  process: {
    title: string;
    intro?: string | null;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  services: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
    intro?: string | null;
  };
  stages: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
    intro?: string | null;
    stage1: {
      name: string;
      lead: string;
      /**
       * Um ponto por linha.
       */
      points?: string | null;
    };
    stage2: {
      name: string;
      lead: string;
      /**
       * Um ponto por linha.
       */
      points?: string | null;
    };
    /**
     * Usada nas páginas das versões que têm Stage 3 sem lista de peças.
     */
    stage3Hint?: string | null;
    warning?: string | null;
  };
  remap: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
  };
  reviews: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
    intro?: string | null;
    moreButton?: string | null;
  };
  events: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
  };
  contact: {
    /**
     * O texto pequeno acima do título.
     */
    label?: string | null;
    /**
     * Aperte Enter para quebrar a linha no site.
     */
    title: string;
    lead?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos que se repetem em todas as páginas do catálogo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos-remap".
 */
export interface TextosRemap {
  id: number;
  /**
   * Aparece embaixo de todas as tabelas de ganhos.
   */
  disclaimer: string;
  notListed?: {
    title?: string | null;
    text?: string | null;
  };
  /**
   * Lista mostrada na página de cada versão, conforme o tipo de motor.
   */
  benefits?: {
    /**
     * Um benefício por linha.
     */
    turbo?: string | null;
    /**
     * Um benefício por linha.
     */
    diesel?: string | null;
    /**
     * Um benefício por linha.
     */
    aspirado?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Telefone, endereço, CNPJ e redes. Aparecem no topo, no rodapé, no contato e em todos os botões de WhatsApp.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresa".
 */
export interface Empresa {
  id: number;
  name: string;
  category: string;
  cnpj?: string | null;
  slogan?: string | null;
  /**
   * Ex.: Mecânica | Tecnologia | Performance
   */
  signature?: string | null;
  bio?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whatsapp: {
    /**
     * Ex.: (14) 99836-4764
     */
    display: string;
    /**
     * Só números, com 55 e DDD. Ex.: 5514998364764
     */
    number: string;
  };
  address: {
    street: string;
    district: string;
    city: string;
    state: string;
    zip: string;
  };
  /**
   * Ex.: Atendimento com hora marcada
   */
  schedule?: string | null;
  social?: {
    instagram?: string | null;
    instagramHandle?: string | null;
    facebook?: string | null;
    googleReviews?: string | null;
  };
  /**
   * Usado no Google e na prévia dos links. Ex.: https://www.kaijuperformance.pro
   */
  url: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Como o site aparece no Google e quando alguém manda o link no WhatsApp.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Até uns 60 caracteres. É a linha azul do resultado da busca.
   */
  title: string;
  /**
   * Até uns 160 caracteres. O texto cinza embaixo do título.
   */
  description: string;
  /**
   * O que aparece em negrito quando mandam o link no WhatsApp.
   */
  shareTitle?: string | null;
  /**
   * Ideal 1200 × 630 px. Se ficar vazio, usa a imagem com o logotipo.
   */
  shareImage?: (number | null) | Midia;
  /**
   * Opcional. Uma por linha. Ex.: remap Bauru
   */
  keywords?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicial_select".
 */
export interface PaginaInicialSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        line1?: T;
        line2?: T;
        highlight?: T;
        lead?: T;
        primaryButton?: T;
        secondaryButton?: T;
        videoWide?: T;
        posterWide?: T;
        videoTall?: T;
        posterTall?: T;
      };
  about?:
    | T
    | {
        label?: T;
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        motto?: T;
        signatureName?: T;
        signatureTagline?: T;
        signatureLine?: T;
        facts?:
          | T
          | {
              term?: T;
              value?: T;
              id?: T;
            };
        mainPhoto?: T;
        secondPhoto?: T;
        mainCaption?: T;
      };
  process?:
    | T
    | {
        title?: T;
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        label?: T;
        title?: T;
        intro?: T;
      };
  stages?:
    | T
    | {
        label?: T;
        title?: T;
        intro?: T;
        stage1?:
          | T
          | {
              name?: T;
              lead?: T;
              points?: T;
            };
        stage2?:
          | T
          | {
              name?: T;
              lead?: T;
              points?: T;
            };
        stage3Hint?: T;
        warning?: T;
      };
  remap?:
    | T
    | {
        label?: T;
        title?: T;
      };
  reviews?:
    | T
    | {
        label?: T;
        title?: T;
        intro?: T;
        moreButton?: T;
      };
  events?:
    | T
    | {
        label?: T;
        title?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        title?: T;
        lead?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos-remap_select".
 */
export interface TextosRemapSelect<T extends boolean = true> {
  disclaimer?: T;
  notListed?:
    | T
    | {
        title?: T;
        text?: T;
      };
  benefits?:
    | T
    | {
        turbo?: T;
        diesel?: T;
        aspirado?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresa_select".
 */
export interface EmpresaSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  cnpj?: T;
  slogan?: T;
  signature?: T;
  bio?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whatsapp?:
    | T
    | {
        display?: T;
        number?: T;
      };
  address?:
    | T
    | {
        street?: T;
        district?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  schedule?: T;
  social?:
    | T
    | {
        instagram?: T;
        instagramHandle?: T;
        facebook?: T;
        googleReviews?: T;
      };
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  shareTitle?: T;
  shareImage?: T;
  keywords?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}